"""First

Revision ID: a70d27ac8c8b
Revises: 
Create Date: 2020-12-30 20:03:36.603147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a70d27ac8c8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('played_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=False),
    sa.Column('track', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('played_at')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    # ### end Alembic commands ###
